import mongoose from "mongoose";

const leadQuestionSchema = new mongoose.Schema(
  {
    label: { type: String, required: true },
    fieldName: { type: String, required: true },
    required: { type: Boolean, default: false }
  },
  { _id: false }
);

const agentSchema = new mongoose.Schema(
  {
    userId: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true, index: true },
    name: String,
    description: String,
    agentName: { type: String, required: true },
    agentType: { type: String, required: true },
    businessName: { type: String, required: true },
    businessCategory: String,
    businessDescription: String,
    businessWebsite: String,
    businessLocation: String,
    workingHours: String,
    contactNumber: String,
    mainGoal: String,
    secondaryGoal: String,
    avoidInstructions: String,
    confusedInstructions: String,
    services: String,
    pricing: String,
    faqs: String,
    policies: String,
    offers: String,
    additionalInfo: String,
    leadQuestions: [leadQuestionSchema],
    language: {
      type: String,
      enum: ["english", "hindi", "hinglish", "hindi_english", "English", "Hindi", "Hinglish", "Hindi + English"],
      default: "english"
    },
    voiceGender: String,
    voiceStyle: String,
    tone: { type: String, default: "Professional" },
    speakingSpeed: { type: String, default: "Normal" },
    personality: { type: String, default: "Polite" },
    greetingMessage: String,
    fallbackMessage: { type: String, default: "I am not sure about that. Our team will call you back with the right information." },
    endingMessage: { type: String, default: "Thank you for calling. Our team will follow up soon." },
    humanTransferMessage: { type: String, default: "I will ask a team member to contact you shortly." },
    responseStyle: { type: String, default: "short_clear" },
    callMode: { type: String, enum: ["outbound", "test", "callback"], default: "outbound" },
    allowInterruption: { type: Boolean, default: true },
    fastReplyMode: { type: Boolean, default: true },
    leadCaptureEnabled: { type: Boolean, default: true },
    voiceProvider: { type: String, default: "Dograh Default" },
    voiceId: String,
    llmProvider: { type: String, enum: ["gemini", "openai"], default: "gemini" },
    llmModel: String,
    sttProvider: { type: String, default: "openai_whisper" },
    ttsProvider: { type: String, default: "openai_tts" },
    firstMessage: String,
    voiceSpeed: { type: String, default: "Normal" },
    voice: { type: mongoose.Schema.Types.Mixed, default: {} },
    nodes: { type: Array, default: [] },
    workflowNodes: { type: Array, default: [] },
    tools: { type: Array, default: [] },
    settings: { type: mongoose.Schema.Types.Mixed, default: {} },
    knowledgeBaseIds: [{ type: mongoose.Schema.Types.ObjectId, ref: "KnowledgeBase" }],
    telephonyConfigId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "TelephonyConfig",
      default: null,
      set: (value) => value === "" ? null : value
    },
    provider: { type: String, enum: ["custom", "dograh", "vapi", "retell"], default: "custom" },
    providerWorkflowId: { type: String, default: null },
    providerAgentId: { type: String, default: null },
    summaryFormat: String,
    systemPrompt: String,
    dograhWorkflowId: { type: String, default: null },
    dograhWorkflowUuid: String,
    dograhAgentId: String,
    dograhWorkflowName: String,
    connectedPhoneNumber: String,
    callerIdNumber: String,
    telephonyProvider: String,
    dograhStatus: String,
    dograhError: String,
    dograhRawResponse: { type: mongoose.Schema.Types.Mixed },
    dograhNeedsUpdate: { type: Boolean, default: false },
    dograhLastSyncedAt: Date,
    dograhEmbedToken: String,
    dograhWidgetEnabled: { type: Boolean, default: false },
    lastSyncedAt: { type: Date, default: null },
    archivedAt: Date,
    status: { type: String, enum: ["Draft", "Active", "Paused", "Connected", "draft", "active", "archived"], default: "draft" },
    shareableLink: String,
    embedCode: String,
    publicSlug: { type: String, unique: true, sparse: true, index: true },
    isPublic: { type: Boolean, default: false },
    publicChatEnabled: { type: Boolean, default: true },
    publicWebCallEnabled: { type: Boolean, default: false },
    publicTitle: String,
    publicDescription: String,
    publicWelcomeMessage: String,
    totalCalls: { type: Number, default: 0 },
    totalLeads: { type: Number, default: 0 }
  },
  { timestamps: true }
);

export default mongoose.model("Agent", agentSchema);
