import mongoose from "mongoose";

const leadQuestionSchema = new mongoose.Schema(
  {
    label: { type: String, required: true },
    fieldName: { type: String, required: true },
    required: { type: Boolean, default: false }
  },
  { _id: false }
);

const agentSchema = new mongoose.Schema(
  {
    userId: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true, index: true },
    name: String,
    description: String,
    agentName: { type: String, required: true },
    agentType: { type: String, required: true },
    businessName: { type: String, required: true },
    businessCategory: String,
    businessDescription: String,
    businessWebsite: String,
    businessLocation: String,
    workingHours: String,
    contactNumber: String,
    mainGoal: String,
    secondaryGoal: String,
    avoidInstructions: String,
    confusedInstructions: String,
    services: String,
    pricing: String,
    faqs: String,
    policies: String,
    offers: String,
    additionalInfo: String,
    leadQuestions: [leadQuestionSchema],
    language: {
      type: String,
      enum: ["english", "hindi", "hinglish", "hindi_english", "English", "Hindi", "Hinglish", "Hindi + English"],
      default: "english"
    },
    voiceGender: String,
    voiceStyle: String,
    tone: { type: String, default: "Professional" },
    speakingSpeed: { type: String, default: "Normal" },
    personality: { type: String, default: "Polite" },
    greetingMessage: String,
    fallbackMessage: { type: String, default: "I am not sure about that. Our team will call you back with the right information." },
    endingMessage: { type: String, default: "Thank you for calling. Our team will follow up soon." },
    humanTransferMessage: { type: String, default: "I will ask a team member to contact you shortly." },
    responseStyle: { type: String, default: "short_clear" },
    callMode: { type: String, enum: ["outbound", "test", "callback"], default: "outbound" },
    allowInterruption: { type: Boolean, default: true },
    fastReplyMode: { type: Boolean, default: true },
    leadCaptureEnabled: { type: Boolean, default: true },
    voiceProvider: { type: String, default: "Dograh Default" },
    voiceId: String,
    llmProvider: { type: String, enum: ["gemini", "openai"], default: "gemini" },
    llmModel: String,
    sttProvider: { type: String, default: "openai_whisper" },
    ttsProvider: { type: String, default: "openai_tts" },
    firstMessage: String,
    voiceSpeed: { type: String, default: "Normal" },
    voice: { type: mongoose.Schema.Types.Mixed, default: {} },
    nodes: { type: Array, default: [] },
    workflowNodes: { type: Array, default: [] },
    tools: { type: Array, default: [] },
    settings: { type: mongoose.Schema.Types.Mixed, default: {} },
    knowledgeBaseIds: [{ type: mongoose.Schema.Types.ObjectId, ref: "KnowledgeBase" }],
    telephonyConfigId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "TelephonyConfig",
      default: null,
      set: (value) => value === "" ? null : value
    },
    provider: { type: String, enum: ["custom", "dograh", "vapi", "retell"], default: "custom" },
    providerWorkflowId: { type: String, default: null },
    providerAgentId: { type: String, default: null },
    summaryFormat: String,
    systemPrompt: String,
    dograhWorkflowId: { type: String, default: null },
    dograhWorkflowUuid: String,
    dograhAgentId: String,
    dograhWorkflowName: String,
    connectedPhoneNumber: String,
    callerIdNumber: String,
    telephonyProvider: String,
    dograhConnection: String,
    dograhStatus: String,
    dograhSyncStatus: String,
    dograhError: String,
    dograhRawResponse: { type: mongoose.Schema.Types.Mixed },
    dograhNeedsUpdate: { type: Boolean, default: false },
    dograhLastSyncedAt: Date,
    dograhEmbedToken: String,
    dograhWidgetEnabled: { type: Boolean, default: false },
    lastSyncedAt: { type: Date, default: null },
    archivedAt: Date,
    status: { type: String, enum: ["Draft", "Active", "Paused", "Connected", "draft", "active", "archived"], default: "draft" },
    shareableLink: String,
    embedCode: String,
    publicSlug: { type: String, unique: true, sparse: true, index: true },
    isPublic: { type: Boolean, default: false },
    publicChatEnabled: { type: Boolean, default: true },
    publicWebCallEnabled: { type: Boolean, default: false },
    publicTitle: String,
    publicDescription: String,
    publicWelcomeMessage: String,
    bioPage: {
      template: { type: String, default: "classic_business" },
      logoUrl: { type: String, default: "" },
      coverImageUrl: { type: String, default: "" },
      agentImageUrl: { type: String, default: "" },
      primaryColor: { type: String, default: "#2563EB" },
      backgroundColor: { type: String, default: "#F8FAFC" },
      textColor: { type: String, default: "#0F172A" },
      buttonColor: { type: String, default: "#2563EB" },
      cardColor: { type: String, default: "#FFFFFF" },
      accentColor: { type: String, default: "#DBEAFE" },
      fontStyle: { type: String, default: "modern" },
      animation: { type: String, default: "fade_in" },
      headline: { type: String, default: "" },
      subheadline: { type: String, default: "" },
      welcomeMessage: { type: String, default: "" },
      ctaText: { type: String, default: "Talk to AI Agent" },
      primaryCtaText: { type: String, default: "Talk to AI Agent" },
      secondaryCtaText: { type: String, default: "Book Appointment" },
      voiceCallCtaText: { type: String, default: "Voice Call" },
      showWebCall: { type: Boolean, default: true },
      showWebCallButton: { type: Boolean, default: true },
      showAppointment: { type: Boolean, default: true },
      showAppointmentButton: { type: Boolean, default: true },
      showContactForm: { type: Boolean, default: false },
      showBusinessInfo: { type: Boolean, default: true },
      showSocialLinks: { type: Boolean, default: false },
      showVoiceCallButton: { type: Boolean, default: true },
      businessInfo: {
        businessName: { type: String, default: "" },
        category: { type: String, default: "" },
        location: { type: String, default: "" },
        availability: { type: String, default: "Online now" },
        responseTime: { type: String, default: "< 30 sec" }
      },
      socialLinks: {
        website: { type: String, default: "" },
        instagram: { type: String, default: "" },
        facebook: { type: String, default: "" },
        whatsapp: { type: String, default: "" },
        linkedin: { type: String, default: "" }
      },
      quickTopics: [
        {
          id: String,
          title: String,
          description: String,
          icon: String,
          iconType: { type: String, enum: ["lucide", "emoji", "image"], default: "lucide" },
          iconImageUrl: String,
          color: String,
          prompt: String,
          isVisible: { type: Boolean, default: true },
          order: Number
        }
      ],
      isPublished: { type: Boolean, default: true },
      updatedAt: Date
    },
    totalCalls: { type: Number, default: 0 },
    totalLeads: { type: Number, default: 0 }
  },
  { timestamps: true }
);

export default mongoose.model("Agent", agentSchema);
